const Rastline = {
    IIllyrica1: require('./assets/rastline/1_Iris illyrica.jpg'),
    IIllyrica2: require('./assets/rastline/2 Iris illyrica.jpg'),
    IIllyrica3: require('./assets/rastline/3 Iris illyrica.jpg'),
    IIllyrica4: require('./assets/rastline/4 Iris illyrica.jpg'),
    AAltisima: require('./assets/rastline/Ailanthus_altissima_sken.jpg'),
    ADonax: require('./assets/rastline/Arundo_donax_sken.jpg'),
    ASquamatus: require('./assets/rastline/Aster_squamatus_sken.jpg'),
    ATripolium: require('./assets/rastline/Aster_tripolium_sken.jpg'),
    APortulacoides: require('./assets/rastline/Atriplex_portulacoides_sken.jpg'),
    CSpicatum: require('./assets/rastline/Centaurium_spicatum_sken.jpg'),
    FAngustifolia: require('./assets/rastline/Fraxinus_angustifolia_sken.jpg'),
    GBilobaA: require('./assets/rastline/Ginkgo_biloba_akvarel.png'),
    GBilobaP: require('./assets/rastline/Ginkgo_biloba_penink.png'),
    ICrithmoides: require('./assets/rastline/Inula_crithmoides_sken.jpg'),
    IIllyricaP: require('./assets/rastline/Iris illyrica_penink.jpg'),
    JMaritimus: require('./assets/rastline/Juncus_maritimus_sken.jpg'),
    LAngustifolium: require('./assets/rastline/Limonium_angustifolium_sken.png'),
    LMaritimum: require('./assets/rastline/Linum_maritimum_sken.jpg'),
    OEuropea: require('./assets/rastline/Olea_europaea.jpg'),
    PAustralis: require('./assets/rastline/Phragmites_australis_sken.jpg'),
    IIllyr: require('./assets/rastline/1_Iris illyrica.jpg'),
    IIllyr: require('./assets/rastline/2 Iris illyrica.jpg'),
    IIllyr: require('./assets/rastline/3 Iris illyrica.jpg'),
    IIllyr: require('./assets/rastline/4 Iris illyrica.jpg'),
    AAlti: require('./assets/rastline/Ailanthus_altissima_sken.jpg'),
    AD: require('./assets/rastline/Arundo_donax_sken.jpg'),
    ASquam: require('./assets/rastline/Aster_squamatus_sken.jpg'),
    ATripo: require('./assets/rastline/Aster_tripolium_sken.jpg'),
    APortulaco: require('./assets/rastline/Atriplex_portulacoides_sken.jpg'),
    CSpic: require('./assets/rastline/Centaurium_spicatum_sken.jpg'),
    FAngustif: require('./assets/rastline/Fraxinus_angustifolia_sken.jpg'),
    GBil: require('./assets/rastline/Ginkgo_biloba_akvarel.png'),
    GBil: require('./assets/rastline/Ginkgo_biloba_penink.png'),
    ICrithmo: require('./assets/rastline/Inula_crithmoides_sken.jpg'),
    IIllyr: require('./assets/rastline/Iris illyrica_penink.jpg'),
    JMarit: require('./assets/rastline/Juncus_maritimus_sken.jpg'),
    LAngustifo: require('./assets/rastline/Limonium_angustifolium_sken.png'),
    LMarit: require('./assets/rastline/Linum_maritimum_sken.jpg'),
    OEur: require('./assets/rastline/Olea_europaea.jpg'),
    PAustr: require('./assets/rastline/Phragmites_australis_sken.jpg')
}

export default Rastline

